pipeline {
	agent any

    stages {
        stage('init') {
            steps {
                checkout scm
                //git credentialsId: '0c388efc-1df3-4013-909a-a0618a6a6882', url: 'https://github.com/ron-liu/shorten-url.git'
            }
        }
        stage('build') {
            steps {
                nodejs('6') {
                    sh 'npm run build'
                }
            }
        }
        stage('test') {
            steps {
                nodejs('6') {
                    sh 'npm run test:ci'
                }
                junit 'web/junit.xml'
                junit 'server/junit.xml'
            }
        }
        stage('deploy') {
            steps {
                dir('web') {
                    //sh 'cp ../src/main/docker/base/Dockerfile .'
                    azureWebAppPublish azureCredentialsId: env.AZURE_CRED_ID, publishType: 'docker',
                         resourceGroup: env.WEB_APP_GROUP, appName: env.WEB_APP_NAME,
                         dockerImageName: "$env.ACR_LOGIN_SERVER/web-app", dockerImageTag: "$env.BUILD_NUMBER",
                         dockerRegistryEndpoint: [url: "http://$env.ACR_LOGIN_SERVER", credentialsId: env.ACR_CRED_ID]
                }
            }
        }
    }
}
